#!/usr/bin/env bash
# Install load balancer

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
echo "
frontend belbouk_tech_frontend
        bind *:80
        timeout client 60s
        default_backend belbouk_tech_backend

backend belbouk_tech_backend
        balance roundrobin
        server 394542-web-01 54.210.88.234:80 check
        server 394542-web-02 34.202.158.245:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
