#!/usr/bin/env bash
# Bash script that install the ufw firewall and setup a few rules
sudo apt-get update
sudo apt-get install ufw

sudo ufw allow 22/tcp   # Allow SSH
sudo ufw allow 80/tcp   # Allow HTTP
sudo ufw allow 443/tcp  # Allow HTTPS

sudo ufw enable