#!/usr/bin/env bash
# script that configures an Ubuntu server.

cp /etc/hosts ~/hosts.new

# replace 127.0.0.1 with 127.0.0.1
sed -i 's/127\.0\.0\.1/127.0.0.2/g' ~/hosts.new
# Remove Facebook configuration if exists
sed -i '/facebook\.com/d' ~/hosts.new
# Add the new Facebook configuration
echo -e "\n8.8.8.8 facebook.com" >> ~/hosts.new

cp -f ~/hosts.new /etc/hosts